{
 "title": "ikuai",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "dsIkuai", "label": "数据源", "query": "prometheus" },
   { "name": "jobName", "label": "采集器", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(ikuai_version{job=\"$jobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "连接状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_up{id=\"host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统版本",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_version{job=\"$jobName\",instance=\"$instance\", }",
     "legendFormat": "iKuai {{verstring}}"
    }
   ]
  },
  {
   "title": "在线设备",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_device_count{job=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_cpu_usage_ratio{job=\"$jobName\", instance=\"$instance\", id!=\"core/0\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "综合负载",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_cpu_usage_ratio{instance=\"$instance\", job=\"$jobName\", id=\"core/0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "设备流量",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(increase(ikuai_network_send_bytes{id=~\"device/.*\", job=\"$jobName\",instance=\"$instance\"}[$__range]) * on(id, instance) group_left(comment, ip_addr) ikuai_device_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(ikuai_network_recv_bytes{id=~\"device/.*\", job=\"$jobName\",instance=\"$instance\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "线路流量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_send_bytes{id!~\"device/.*|.*lan.*\", instance=\"$instance\", job=\"$jobName\"}",
     "legendFormat": "上行 {{id}}"
    },
    {
     "expr": "ikuai_network_recv_bytes{id!~\"device/.*|.*lan.*\", job=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "下行 {{id}}"
    }
   ]
  },
  {
   "title": "DHCP池剩余",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_dhcp_addrpool_num{job=\"$jobName\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_uptime{id=\"host\", job=\"$jobName\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_network_conn_count{id=\"host\", job=\"$jobName\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ikuai_memory_usage_bytes{ job=\"$jobName\",instance=\"$instance\"}/ikuai_memory_size_bytes{job=\"$jobName\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最近30分钟流量分布",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(category) (ikuai_app_flow_histogram_sum{job=\"$jobName\", instance=\"$instance\"})",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "设备流量 - 实时",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(ikuai_network_send_kbytes_per_second{id=~\"device/.*\", job=\"$jobName\",instance=\"$instance\"}* on (id, instance) group_left(ip_addr, hostname, comment, mac) ikuai_device_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=~\"device/.*\", job=\"$jobName\",instance=\"$instance\"} * on (id) group_left(ip_addr, hostname, comment, mac) ikuai_device_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "ikuai_network_conn_count{id=~\"device/.*\", job=\"$jobName\",instance=\"$instance\"} * on (id) group_left ikuai_device_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "主机流量 - 实时",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ikuai_network_send_kbytes_per_second{id=\"host\", job=\"$jobName\",instance=\"$instance\"}",
     "legendFormat": "⏫"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=\"host\", job=\"$jobName\",instance=\"$instance\"}*-1",
     "legendFormat": "⏬"
    }
   ]
  },
  {
   "title": "线路流量 - 实时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(ikuai_network_send_kbytes_per_second{id=~\"iface/.*\",job=\"$jobName\",instance=\"$instance\"} and on(id) ikuai_uptime > 0) * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}({{interface}})⏫"
    },
    {
     "expr": "(ikuai_network_recv_kbytes_per_second{id=~\"iface/.*\",job=\"$jobName\",instance=\"$instance\"}*-1 and on(id) ikuai_uptime > 0) * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}({{interface}})⏬"
    }
   ]
  },
  {
   "title": "设备流量 - 实时",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "  (\r\n      ikuai_network_recv_kbytes_per_second{id=~\"device/.*\", job=\"$jobName\", instance=\"$instance\"}\r\n    +\r\n      ikuai_network_send_kbytes_per_second{id=~\"device/.*\", job=\"$jobName\", instance=\"$instance\"}\r\n  )\r\n* on (id) group_left (mac, comment)\r\n  (max by (id, mac, comment) (ikuai_device_info{id=~\"device/.*\", job=\"$jobName\", instance=\"$instance\"}))",
     "legendFormat": "{{comment}}({{mac}})"
    }
   ]
  },
  {
   "title": "历史连接数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ikuai_network_conn_count{id=~\"device/.*\", job=\"$jobName\", instance=\"$instance\"} * on (id) group_left (mac, comment)\r\n  (max by (id, mac, comment) (ikuai_device_info{id=~\"device/.*\", job=\"$jobName\", instance=\"$instance\"}))",
     "legendFormat": "{{comment}}({{mac}})"
    }
   ]
  },
  {
   "title": "线路流量 - 实时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "ikuai_network_send_kbytes_per_second{id=~\"iface/.*\", job=\"$jobName\",instance=\"$instance\"} * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}({{interface}})⏫"
    },
    {
     "expr": "ikuai_network_recv_kbytes_per_second{id=~\"iface/.*\",job=\"$jobName\",instance=\"$instance\"} * on (id) group_left(interface, comment) ikuai_iface_info",
     "legendFormat": "{{comment}}({{interface}})⏬"
    }
   ]
  }
 ]
}